"""create Role table

Revision ID: 1541d897ded8
Revises: 068c0639bf77
Create Date: 2026-02-11 17:27:43.272078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1541d897ded8'
down_revision: Union[str, Sequence[str], None] = '068c0639bf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column(
        'accounts',
        'role_id',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using='role_id::integer',
    )
    op.create_foreign_key(
        'accounts_role_id_fkey',
        'accounts',
        'roles',
        ['role_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_role_id_fkey', 'accounts', type_='foreignkey')
    op.alter_column('accounts', 'role_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('roles')
    # ### end Alembic commands ###
